@startuml

<style>
element {
    MaximumWidth 200
}
</style>

skinparam shadowing false
skinparam dpi 150

skinparam swimlaneTitleFontSize 16
skinparam swimlaneTitleFontColor Black
skinparam swimlaneTitleFontStyle bold

skinparam activity {
    BackgroundColor White
    BorderColor Black
    FontSize 14
    DiamondFontSize 14
}

|Notifier|

start

:1. Notification d'un OPINAC;

|Reporter|

:2. Enregistrement de l'OPINAC;

|Safety|

:3. Vérification et assignation;

|Technical|

:4. Analyse préliminaire;

|Safety|

:5. Analyse approfondie;

|Management|

:6. Approbation OPINAC RPT;

repeat

|Safety|

:7. Affectation des mesures;

|Assignee|

:8. Préparation et planification;

:9. Exécution des mesures;

|Safety|

:10. Vérification des mesures;

repeat while (11. Validation ?) is (Non) not (Oui)

:12. Clôture de l'OPINAC;

:13. Information de l'initiateur;

stop

@enduml