@startwbs

skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 18
skinparam RoundCorner 12
skinparam legendFontName Arial
skinparam legendFontSize 18

<style>
element {
    MaximumWidth 760
}
</style>

* ⚠ OPINAC 50 - Incidents sur les PNs de L54 & L57

** 🔵 EVT01 - Modification de la logique des PN sur les L54 et L57

*** 🟡 C02 - Positionnement incorrect du ELSE dans la modification proposée

**** 🔴 RC01 - Non-respect des prescriptions imposant la validation des déviations au formalisme avant la mise en service

***** 🟢 M01A - Adapter le processus de gestion des modifications de dataprep lors de déviation par rapport au formalisme des notices
***** 🟢 M01B - Introduire un point de contrôle formel de l'application du processus

**** 🔴 RC02 - Périmètre de test insuffisant

***** 🟢 M02A - Formaliser le contrôle des L_ utilisés pour l'inhibition des ZAX
***** 🟢 M02B - Considérer améliorer les lignes directrices pour déterminer le périmètre des essais
***** 🟢 M02C - Développer un outil d'assistance à la préparation des plans de tests

*** 🟣 CONS01 - Passage de trains avec PN ouverts et signaux routiers permissifs\n12 PN impactés - Situation de quasi-accident

**** 🔵 EVT02 - Correction de la dataprep en cas d'incident

***** 🟡 C03 - Oubli de correction de la dataprep

****** 🔴 RC03 - Absence de processus de gestion d'incident assurant la disponibilité des ressources, des moyens d'essai et des contrôles requis avant la remise en service

******* 🟢 M03 - Mettre en place un processus de gestion des incidents garantissant la disponibilité des ressources, l'indépendance des rôles et les moyens nécessaires à la réalisation des essais.

***** 🟣 CONS02 - Un PN de la L54 à nouveau détecté ouvert au passage d'un train

****** 🟢 M04 - Diffusion du retour d'expérience auprès des acteurs concernés


legend right
  🔵 Événement initiateur
  🟡 Cause directe
  🔴 Cause racine
  🟢 Mesure
  🟣 Conséquence
endlegend

@endwbs